# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Master Merged Check

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: PR Build 
    uses: ./.github/workflows/test.yaml
    
    
