# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  pr_comment_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check for "retest" keyword
        id: check_keyword
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueComment = context.payload.comment.body;
            const retestKeyword = 'retest';
            if (issueComment.includes(retestKeyword)) {
              return true;
            } else {
              return false;
            }

      - name: Get Result
        run: echo "${{steps.check_keyword.outputs.result}}"

      - name: Run specific action
        if: steps.check_keyword.outputs.result
        uses: echo "Must Implement!!"
          
      - name: printMessage
        run: echo "Success"
          
