# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  pr_comment_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check for "retest" keyword
        id: check_keyword
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const keyword = 'retest';
            const comment = context.payload.comment.body;
            const regex = new RegExp(keyword, 'i');
            const shouldTrigger = regex.test(comment);
            console.log(`PR Comment: ${comment}`);
            console.log(`Should Trigger Retest: ${shouldTrigger}`);
            console.log(`Workflow File: .github/workflows/reusable-workflow.yml`);
            core.setOutput('trigger-retest', shouldTrigger)
            
            const issueComment = context.payload.comment.body;
            if (issueComment.includes(keyword)) {
              return true;
            } else {
              return false;
            }

      - name: Get Result
        run: |
          echo "${{steps.check_keyword.outputs.result}}"
          echo "${{steps.check_keyword.outputs.trigger-retest}}"
        
      - name: If Check
        if: ${{steps.check_keyword.outputs.result == 'true'}}
        run: echo "Hello!!"
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run action!
        if: ${{steps.check_keyword.outputs.result == 'true'}}
        uses: ./.github/workflows/test.yaml
          
      - name: printMessage
        run: echo "Success"
          
